// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFFOMVg7H7wtgUU4wu8KLKAEjXvWfIFGA',
    appId: '1:74410548711:web:37113fc78a92804c327142',
    messagingSenderId: '74410548711',
    projectId: 'authdemo-9f528',
    authDomain: 'authdemo-9f528.firebaseapp.com',
    storageBucket: 'authdemo-9f528.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByWKWLPhtYGqlmQIYiAY2rq-cDmeLiTTQ',
    appId: '1:554774423519:android:b5fcccc377e86e069d466a',
    messagingSenderId: '554774423519',
    projectId: 'filidides',
    storageBucket: 'filidides.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-m5DG4NlHtsNB9PoZkefDfMH2_2Es2fg',
    appId: '1:74410548711:ios:1a58c92df670a14c327142',
    messagingSenderId: '74410548711',
    projectId: 'authdemo-9f528',
    storageBucket: 'authdemo-9f528.firebasestorage.app',
    iosBundleId: 'fr.graven.authdemo.authDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-m5DG4NlHtsNB9PoZkefDfMH2_2Es2fg',
    appId: '1:74410548711:ios:1a58c92df670a14c327142',
    messagingSenderId: '74410548711',
    projectId: 'authdemo-9f528',
    storageBucket: 'authdemo-9f528.firebasestorage.app',
    iosBundleId: 'fr.graven.authdemo.authDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFFOMVg7H7wtgUU4wu8KLKAEjXvWfIFGA',
    appId: '1:74410548711:web:4971d4cc85784d32327142',
    messagingSenderId: '74410548711',
    projectId: 'authdemo-9f528',
    authDomain: 'authdemo-9f528.firebaseapp.com',
    storageBucket: 'authdemo-9f528.firebasestorage.app',
  );
}
